# Generated by Django 3.2.9 on 2022-02-08 08:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220208_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2002, 2, 13, 8, 25, 34, 78387, tzinfo=utc), verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='手机号码'),
        ),
    ]
