# Generated by Django 3.2.9 on 2022-02-11 03:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220208_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pre_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.comment', verbose_name='原评论'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='blog.articlepost', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='birthday',
            field=models.DateField(default=datetime.date(2002, 2, 16), verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='img',
            field=models.ImageField(default='image/user/default.png', upload_to='image/user/%Y/%m/%d/', verbose_name='头像'),
        ),
    ]
